{
    "openapi": "3.0.0",
    "info": {
        "title": "Forwarder API",
        "version": "1.0.0"
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/api/user/create": {
            "post": {
                "tags" : ["User"],
                "summary": "Create User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "User's name",
                                        "example": "John Doe"
                                    },
                                    "phone": {
                                        "type": "string",
                                        "description": "User's phone number",
                                        "example": "+1234567890"
                                    },
                                    "email": {
                                        "type": "string",
                                        "description": "User's email address",
                                        "example": "john@example.com"
                                    },
                                    "user_role_id": {
                                        "type": "integer",
                                        "description": "User's role ID",
                                        "example": 1
                                    },
                                    "standard": {
                                        "type": "string",
                                        "description": "Standard User information",
                                        "example": {
                                            "lastName" : "doe",
                                            "private_number" : "59009102",
                                            "position" : "CTO"
                                        }
                                    },
                                    "driver": {
                                        "type": "string",
                                        "description": "Driver information",
                                        "example": {
                                            "telegram" : "59009102",
                                            "whatsapp" : "59009102",
                                            "viber" : "59009102",
                                            "referral_code" : "a134",
                                            "iban" : "GE34BG132134",
                                            "car" : {
                                                "id": {
                                                    "type": "integer",
                                                    "description": "Car's id",
                                                    "example": 5
                                                },
                                                "number": {
                                                    "type": "string",
                                                    "description": "Car Number",
                                                    "example": "WW-101-ZZ"
                                                },
                                                "title": {
                                                    "type": "string",
                                                    "description": "Car Title",
                                                    "example": "Audi"
                                                },
                                                "model": {
                                                    "type": "string",
                                                    "description": "Car Model",
                                                    "example": "A8"
                                                },
                                                "identification_number": {
                                                    "type": "string",
                                                    "description": "Identification Number",
                                                    "example": "1234567"
                                                },
                                                "car_type_id": {
                                                    "type": "integer",
                                                    "description": "relation from car_types",
                                                    "example": 1
                                                },
                                                "tech_passport": {
                                                    "type": "string",
                                                    "description": "Image",
                                                    "example": "Image file"
                                                }
                                            },
                                            "trailer" : {
                                                "id": {
                                                    "type": "integer",
                                                    "description": "Trailer's id",
                                                    "example": 5
                                                },
                                                "number": {
                                                    "type": "string",
                                                    "description": "Trailer Number",
                                                    "example": "WW-101-ZZ"
                                                },
                                                "title": {
                                                    "type": "string",
                                                    "description": "Trailer Title",
                                                    "example": "Audi"
                                                },
                                                "model": {
                                                    "type": "string",
                                                    "description": "Trailer Model",
                                                    "example": "A8"
                                                },
                                                "identification_number": {
                                                    "type": "string",
                                                    "description": "Identification Number",
                                                    "example": "1234567"
                                                },
                                                "trailer_type_id": {
                                                    "type": "integer",
                                                    "description": "relation from trailer_types",
                                                    "example": 1
                                                },
                                                "tech_passport": {
                                                    "type": "string",
                                                    "description": "Image",
                                                    "example": "Image file"
                                                }
                                            }
                                        }
                                    },
                                    "legal": {
                                        "type": "string",
                                        "description": "Legal entity information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "forwarder": {
                                        "type": "string",
                                        "description": "Forwarder information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "customer": {
                                        "type": "string",
                                        "description": "Customer information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "languages" : {
                                        "type" : "array",
                                        "description" : "User Languages",
                                        "example" : [1,2,3,4]
                                    },
                                    "images": {
                                        "type": "string",
                                        "description": "Image URLs",
                                        "example": [
                                            {
                                                "title" : "drivers_license",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "tech_passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "residence_confirmation",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "bank_credentials",
                                                "url" : "https://shorturl.at/moNP0"
                                            }
                                        ]
                                    }
                                },
                                "required": ["name", "phone", "email"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User registration successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user/update/{id}": {
            "put": {
                "tags" : ["User"],
                "summary": "Update User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "User's name",
                                        "example": "John Doe"
                                    },
                                    "phone": {
                                        "type": "string",
                                        "description": "User's phone number",
                                        "example": "+1234567890"
                                    },
                                    "email": {
                                        "type": "string",
                                        "description": "User's email address",
                                        "example": "john@example.com"
                                    },
                                    "user_role_id": {
                                        "type": "integer",
                                        "description": "User's role ID",
                                        "example": 1
                                    },
                                    "standard": {
                                        "type": "string",
                                        "description": "Standard User information",
                                        "example": {
                                            "lastName" : "doe",
                                            "private_number" : "59009102",
                                            "position" : "CTO"
                                        }
                                    },
                                    "driver": {
                                        "type": "string",
                                        "description": "Driver information",
                                        "example": {
                                            "telegram" : "59009102",
                                            "whatsapp" : "59009102",
                                            "viber" : "59009102",
                                            "referral_code" : "a134",
                                            "iban" : "GE34BG132134",
                                            "car" : {
                                                "id": {
                                                    "type": "integer",
                                                    "description": "Car's id",
                                                    "example": 5
                                                },
                                                "number": {
                                                    "type": "string",
                                                    "description": "Car Number",
                                                    "example": "WW-101-ZZ"
                                                },
                                                "title": {
                                                    "type": "string",
                                                    "description": "Car Title",
                                                    "example": "Audi"
                                                },
                                                "model": {
                                                    "type": "string",
                                                    "description": "Car Model",
                                                    "example": "A8"
                                                },
                                                "identification_number": {
                                                    "type": "string",
                                                    "description": "Identification Number",
                                                    "example": "1234567"
                                                },
                                                "car_type_id": {
                                                    "type": "integer",
                                                    "description": "relation from car_types",
                                                    "example": 1
                                                },
                                                "tech_passport": {
                                                    "type": "string",
                                                    "description": "Image",
                                                    "example": "Image file"
                                                }
                                            },
                                            "trailer" : {
                                                "id": {
                                                    "type": "integer",
                                                    "description": "Trailer's id",
                                                    "example": 5
                                                },
                                                "number": {
                                                    "type": "string",
                                                    "description": "Trailer Number",
                                                    "example": "WW-101-ZZ"
                                                },
                                                "title": {
                                                    "type": "string",
                                                    "description": "Trailer Title",
                                                    "example": "Audi"
                                                },
                                                "model": {
                                                    "type": "string",
                                                    "description": "Trailer Model",
                                                    "example": "A8"
                                                },
                                                "identification_number": {
                                                    "type": "string",
                                                    "description": "Identification Number",
                                                    "example": "1234567"
                                                },
                                                "trailer_type_id": {
                                                    "type": "integer",
                                                    "description": "relation from trailer_types",
                                                    "example": 1
                                                },
                                                "tech_passport": {
                                                    "type": "string",
                                                    "description": "Image",
                                                    "example": "Image file"
                                                }
                                            }
                                        }
                                    },
                                    "legal": {
                                        "type": "string",
                                        "description": "Legal entity information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "forwarder": {
                                        "type": "string",
                                        "description": "Forwarder information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "customer": {
                                        "type": "string",
                                        "description": "Customer information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "languages" : {
                                        "type" : "array",
                                        "description" : "User Languages",
                                        "example" : [1,2,3,4]
                                    },
                                    "images": {
                                        "type": "string",
                                        "description": "Image URLs",
                                        "example": [
                                            {
                                                "title" : "drivers_license",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "tech_passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "residence_confirmation",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "bank_credentials",
                                                "url" : "https://shorturl.at/moNP0"
                                            }
                                        ]
                                    }
                                },
                                "required": ["name", "phone", "email"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Updated successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user/delete/{id}": {
            "delete": {
                "tags" : ["User"],
                "summary": "Delete User",
                "responses": {
                    "200": {
                        "description": "User Deleted successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags" : ["User"],
                "summary": "Current User",
                "responses": {
                    "200": {
                        "description": "Current user fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user/roles": {
            "get": {
                "tags" : ["User"],
                "summary": "User Roles",
                "responses": {
                    "200": {
                        "description": "User Roles fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/user/verify": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Verify User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "user_id": {
                                        "type": "integer",
                                        "description": "User ID",
                                        "example": 123
                                    },
                                    "otp": {
                                        "type": "integer",
                                        "description": "verification Code",
                                        "example": 123456
                                    }
                                },
                                "required": ["user_id", "otp"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Verified successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user/get-login-code": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Get Login code",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "phone": {
                                        "type": "string",
                                        "description": "User Phone number",
                                        "example": "+1234567890"
                                    }
                                },
                                "required": ["phone"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Code sent successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Login User with code",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "phone": {
                                        "type": "string",
                                        "description": "User Phone number",
                                        "example": "+1234567890"
                                    },
                                    "otp": {
                                        "type": "string",
                                        "description": "User OTP code",
                                        "example": "123456"
                                    }
                                },
                                "required": ["phone", "otp"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Logged in successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/car/types": {
            "get": {
                "tags" : ["Car"],
                "summary": "Car types",
                "responses": {
                    "200": {
                        "description": "Car types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/car/create": {
            "post": {
                "tags" : ["Car"],
                "summary": "Create/Update Car",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer",
                                        "description": "Car's id",
                                        "example": 5
                                    },
                                    "number": {
                                        "type": "string",
                                        "description": "Car Number",
                                        "example": "WW-101-ZZ"
                                    },
                                    "title": {
                                        "type": "string",
                                        "description": "Car Title",
                                        "example": "Audi"
                                    },
                                    "model": {
                                        "type": "string",
                                        "description": "Car Model",
                                        "example": "A8"
                                    },
                                    "identification_number": {
                                        "type": "string",
                                        "description": "Identification Number",
                                        "example": "1234567"
                                    },
                                    "car_type_id": {
                                        "type": "integer",
                                        "description": "relation from car_types",
                                        "example": 1
                                    },
                                    "tech_passport": {
                                        "type": "string",
                                        "description": "Image",
                                        "example": "Image file"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Car types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/trailer/types": {
            "get": {
                "tags" : ["Trailer"],
                "summary": "Trailer types",
                "responses": {
                    "200": {
                        "description": "Trailer types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/trailer/create": {
            "get": {
                "tags" : ["Trailer"],
                "summary": "Create/Update Trailer",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer",
                                        "description": "Car's id",
                                        "example": 5
                                    },
                                    "number": {
                                        "type": "string",
                                        "description": "Car Number",
                                        "example": "WW-101-ZZ"
                                    },
                                    "title": {
                                        "type": "string",
                                        "description": "Car Title",
                                        "example": "Audi"
                                    },
                                    "model": {
                                        "type": "string",
                                        "description": "Car Model",
                                        "example": "A8"
                                    },
                                    "identification_number": {
                                        "type": "string",
                                        "description": "Identification Number",
                                        "example": "1234567"
                                    },
                                    "trailer_type_id": {
                                        "type": "integer",
                                        "description": "relation from car_types",
                                        "example": 1
                                    },
                                    "tech_passport": {
                                        "type": "string",
                                        "description": "Image",
                                        "example": "Image file"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Trailer types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/language": {
            "get": {
                "tags" : ["Language"],
                "summary": "All Languages",
                "responses": {
                    "200": {
                        "description": "Languages fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/rs/tax-payer/{code}": {
            "get": {
                "tags" : ["RS"],
                "summary": "Tax payer info",
                "parameters": [
                    {
                        "in": "path",
                        "name": "code",
                        "description": "Tax payer code",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "206322102"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tax Payer info fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/api/chat" : {
            "post": {
                "tags" : ["Chat"],
                "summary": "Send Message",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "sender_id": {
                                        "type": "integer",
                                        "description": "Message Sender ID",
                                        "example": 1
                                    },
                                    "receiver_id": {
                                        "type": "integer",
                                        "description": "Message Receiver ID",
                                        "example": 2
                                    },
                                    "message": {
                                        "type": "string",
                                        "description": "Message Description",
                                        "example": "Hello my friend"
                                    }

                                },
                                "required": ["sender_id", "receiver_id", "message"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Message has been successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/chat/{senderId}": {
            "get": {
                "parameters": [
                    {
                        "in": "path",
                        "name": "senderId",
                        "description": "Sender ID",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": 2
                        }
                    },
                ],
                "tags" : ["Chat"],
                "summary": "Get Conversations",
                "responses": {
                    "200": {
                        "description": "Conversations fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/chat/show/{senderId}/{receiverId}": {
            "get": {
                "parameters": [
                    {
                        "in": "path",
                        "name": "senderId",
                        "description": "Sender ID",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": 2
                        }
                    },
                    {
                        "in": "path",
                        "name": "receiverId",
                        "description": "Receiver ID",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": 4
                        }
                    }
                ],
                "tags" : ["Chat"],
                "summary": "Get Single Conversation",
                "responses": {
                    "200": {
                        "description": "Conversation fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    }
}
